//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_real_estate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csharp_real_estate_dbEntities : DbContext
    {
        public csharp_real_estate_dbEntities()
            : base("name=csharp_real_estate_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<collections_galery> collections_galery { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<news_comment> news_comment { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<products_galery> products_galery { get; set; }
        public virtual DbSet<subscribed> subscribeds { get; set; }
    }
}
