//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_real_estate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.products_galery = new HashSet<products_galery>();
            this.products_galery1 = new HashSet<products_galery>();
            this.products_galery2 = new HashSet<products_galery>();
        }
    
        public int products_id { get; set; }
        public string products_name { get; set; }
        public string products_slug { get; set; }
        public string area { get; set; }
        public string information { get; set; }
        public string desciption { get; set; }
        public string address { get; set; }
        public decimal price { get; set; }
        public int type { get; set; }
        public int viewCount { get; set; }
        public bool isHot { get; set; }
        public int collections_id { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual collection collection1 { get; set; }
        public virtual collection collection2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_galery> products_galery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_galery> products_galery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_galery> products_galery2 { get; set; }
    }
}
